title: M Divyadarshini
logo: assets/image/divya_rectangle_headshot.jpg
description: >
  PhD Scholar in Computer Vision & Deep Learning | ML Engineer with (2+ years) in model training, fine-tuning and deployment. Specialized in biomedical imaging and GenAI systems, with strong expertise in VLMs, optimization techniques.
show_downloads: false
theme: jekyll-theme-minimal
